apiVersion: v1
kind: Service
metadata:
  name: python-service
  labels:
    app: python
spec:
  ports:
    - nodePort: 30000
      port: 80
      targetPort: 80
  selector:
    app: python
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: python-pv-claim
  labels:
    app: python
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: python-pod
  labels:
    app: python
spec:
  selector:
    matchLabels:
      app: python
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - image: shivam161099/apache-php-python:v1
        name: python
        ports:
        - containerPort: 30000
          name: python
        volumeMounts:
        - name: python-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: python-persistent-storage 
        persistentVolumeClaim:
          claimName: python-pv-claim